### PR TITLE
added details in http errors

### PR DESCRIPTION
**Pull request by victorfour**
Couldn't figure out what went wrong the first time i tried to run the bot, so i figured it would be a good idea to print out http errors.
Also, first try at a pull request.

### CODE REVIEW

**Comment by notatallshaw** [comment]
Looks awesome, I'll merge once I finish work and get home to quickly test.

**Comment by notatallshaw** [comment]
FYI this introduced a minor regression that I'll fix directly on main:

Traceback (most recent call last):
  File "main.py", line 19, in <module>
    main()
  File "main.py", line 16, in main
    arandabot.arandabot(settings=settings)
  File "C:\Users\Damian\Documents\arandabot - test\arandabot.py", line 54, in arandabot
    yt.getNewsestVideos()
  File "C:\Users\Damian\Documents\arandabot - test\ytvideos.py", line 238, in getNewsestVideos
    "\nDetails:\n" + e.content)
TypeError: cannot concatenate 'str' and 'int' objects

**Comment by victorfour** [comment]
sorry about that :/

**Comment by notatallshaw** [comment]
Less than a problem, just thought I'd let you known in tweaked the code to fix this. 

It's probably attributable to me as you were just following my style of string addition rather than string substitution. I know I'm not following the pythononic way of doing things here, I've just been conditioned by years of she'll scripting.

**Pull request merged**
